export const mockData = [
  {
    id: 1,
    creativeId: "120214081337200422",
    creativeName: "Creative 1",
    country: "IN",
    state: "Maharashtra",
    area: "Mumbai",
    place: "Andheri",
    adNetwork: "meta",
    os: "unknown",
    campaign: "Campaign 1",
    adGroup: "Group 1",
    ipm: 2.7,
    ctr: 0.844,
    spend: 100,
    impressions: 1000,
    clicks: 100,
    cpm: 10,
    costPerClick: 1,
    costPerInstall: 10,
    installs: 10,
    tags: ["Pumpkin", "Cat"],
    spends: 100,
  },
  {
    id: 2,
    creativeId: "120214081337200423",
    creativeName: "Creative 2",
    country: "US",
    state: "California",
    area: "Los Angeles",
    place: "Hollywood",
    adNetwork: "google",
    os: "android",
    campaign: "Campaign 2",
    adGroup: "Group 2",
    ipm: 3.5,
    ctr: 1.244,
    spend: 200,
    impressions: 2000,
    clicks: 200,
    cpm: 20,
    costPerClick: 1,
    costPerInstall: 10,
    installs: 20,
    tags: ["Ghost", "Egg"],
    spends: 200,
  },
  {
    id: 3,
    creativeId: "120214081337200424",
    creativeName: "Creative 3",
    country: "UK",
    state: "England",
    area: "London",
    place: "Westminster",
    adNetwork: "meta",
    os: "ios",
    campaign: "Campaign 3",
    adGroup: "Group 3",
    ipm: 1.5,
    ctr: 0.544,
    spend: 150,
    impressions: 1500,
    clicks: 150,
    cpm: 15,
    costPerClick: 1,
    costPerInstall: 10,
    installs: 15,
    tags: ["Color", "Font"],
    spends: 150,
  },
  {
    id: 4,
    creativeId: "120214081337200425",
    creativeName: "Creative 4",
    country: "AU",
    state: "New South Wales",
    area: "Sydney",
    place: "Bondi",
    adNetwork: "meta",
    os: "unknown",
    campaign: "Campaign 4",
    adGroup: "Group 4",
    ipm: 2.8,
    ctr: 0.944,
    spend: 120,
    impressions: 1200,
    clicks: 120,
    cpm: 12,
    costPerClick: 1,
    costPerInstall: 10,
    installs: 12,
    tags: ["Other"],
    spends: 120,
  },
  {
    id: 5,
    creativeId: "120214081337200426",
    creativeName: "Creative 5",
    country: "CA",
    state: "Ontario",
    area: "Toronto",
    place: "Downtown",
    adNetwork: "google",
    os: "ios",
    campaign: "Campaign 5",
    adGroup: "Group 5",
    ipm: 3.0,
    ctr: 1.044,
    spend: 180,
    impressions: 1800,
    clicks: 180,
    cpm: 18,
    costPerClick: 1,
    costPerInstall: 10,
    installs: 18,
    tags: ["Elements", "CTA Position"],
    spends: 180,
  },
  {
    id: 6,
    creativeId: "120214081337200427",
    creativeName: "Creative 6",
    country: "IN",
    state: "Karnataka",
    area: "Bangalore",
    place: "Whitefield",
    adNetwork: "meta",
    os: "android",
    campaign: "Campaign 6",
    adGroup: "Group 6",
    ipm: 2.9,
    ctr: 0.744,
    spend: 110,
    impressions: 1100,
    clicks: 110,
    cpm: 11,
    costPerClick: 1,
    costPerInstall: 10,
    installs: 11,
    tags: ["Pumpkin", "Ghost"],
    spends: 110,
  },
  {
    id: 7,
    creativeId: "120214081337200428",
    creativeName: "Creative 7",
    country: "US",
    state: "Texas",
    area: "Houston",
    place: "Downtown",
    adNetwork: "google",
    os: "ios",
    campaign: "Campaign 7",
    adGroup: "Group 7",
    ipm: 3.2,
    ctr: 1.144,
    spend: 210,
    impressions: 2100,
    clicks: 210,
    cpm: 21,
    costPerClick: 1,
    costPerInstall: 10,
    installs: 21,
    tags: ["Cat", "Egg"],
    spends: 210,
  },
  {
    id: 8,
    creativeId: "120214081337200429",
    creativeName: "Creative 8",
    country: "UK",
    state: "Scotland",
    area: "Edinburgh",
    place: "Leith",
    adNetwork: "meta",
    os: "unknown",
    campaign: "Campaign 8",
    adGroup: "Group 8",
    ipm: 1.8,
    ctr: 0.644,
    spend: 160,
    impressions: 1600,
    clicks: 160,
    cpm: 16,
    costPerClick: 1,
    costPerInstall: 10,
    installs: 16,
    tags: ["Color", "Other"],
    spends: 160,
  },
  {
    id: 9,
    creativeId: "120214081337200430",
    creativeName: "Creative 9",
    country: "AU",
    state: "Victoria",
    area: "Melbourne",
    place: "CBD",
    adNetwork: "google",
    os: "android",
    campaign: "Campaign 9",
    adGroup: "Group 9",
    ipm: 2.6,
    ctr: 0.844,
    spend: 130,
    impressions: 1300,
    clicks: 130,
    cpm: 13,
    costPerClick: 1,
    costPerInstall: 10,
    installs: 13,
    tags: ["Font", "Elements"],
    spends: 130,
  },
  {
    id: 10,
    creativeId: "120214081337200431",
    creativeName: "Creative 10",
    country: "CA",
    state: "British Columbia",
    area: "Vancouver",
    place: "Downtown",
    adNetwork: "meta",
    os: "ios",
    campaign: "Campaign 10",
    adGroup: "Group 10",
    ipm: 3.1,
    ctr: 1.244,
    spend: 190,
    impressions: 1900,
    clicks: 190,
    cpm: 19,
    costPerClick: 1,
    costPerInstall: 10,
    installs: 19,
    tags: ["CTA Position", "CTA Test"],
    spends: 190,
  },
];